edition                        = "2021"
unstable_features              = true                 # Unstable

array_width                    = 100
attr_fn_like_width             = 100
#blank_lines_lower_bound       = 1                    # Unstable
blank_lines_upper_bound        = 3                    # Unstable
chain_width                    = 100
#comment_width                 = 80                   # Unstable
#doc_comment_code_block_width  = 80                   # Unstable
enum_discrim_align_threshold   = 50                   # Unstable
fn_call_width                  = 100
#format_code_in_doc_comments   = true                 # Unstable
format_macro_bodies            = true                 # Unstable
format_macro_matchers          = true                 # Unstable
format_strings                 = true                 # Unstable
group_imports                  = "StdExternalCrate"   # Unstable
hard_tabs                      = true
imports_granularity            = "Crate"              # Unstable
imports_layout                 = "HorizontalVertical" # Unstable
match_arm_leading_pipes        = "Preserve"
match_block_trailing_comma     = true
max_width                      = 120
newline_style                  = "Unix"
overflow_delimited_expr        = true                 # Unstable
reorder_impl_items             = true                 # Unstable
single_line_if_else_max_width  = 100
single_line_let_else_max_width = 100
struct_field_align_threshold   = 50                   # Unstable
#wrap_comments                 = true                 # Unstable

ignore                         = [                    # Unstable
]
